# Supabase Configuration File for WomenSafe App

project_id = "htrmibvimwvldtoncxuw"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 15

[functions.send-emergency-notification]
verify_jwt = false